# -*- coding: utf-8 -*-
"""Car_accident.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azz6pYz-W6gyiPZRdPODJ8bmPaNFGLz8
"""

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.getcwdb())

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/b10801107@gapps.ntust.edu.tw 2022-04-12 00:24/Ariel Data Science/CAR_ACCIDENT/US_Accidents_Dec20.csv")

import numpy as np

df.head()

print(df["Start_Lat"].min(),df["Start_Lat"].max())



print(df["Start_Lng"].min(),df["Start_Lng"].max())

df.info()

df.describe

import matplotlib.pyplot as plt

df["Start_Lng"]

type(df["Severity"][0])



import time
start_time = time.time()

fig = plt.figure(figsize=(15,10))

#plt.scatter(df["Start_Lng"],df["Start_Lat"],s=20,c='r',marker='v',alpha=0.4,label='Simple Assault')


cr_1 = df[df["Severity"] == 1]
plt.scatter(cr_1["Start_Lng"], cr_1["Start_Lat"],s=0.3,c='tab:green',marker='3',alpha=0.1,label='1')

cr_2 = df[df["Severity"] == 2]
plt.scatter(cr_2["Start_Lng"], cr_2["Start_Lat"],s=0.3,c='tab:blue',marker='1',alpha=0.1,label='2')

cr_3 = df[df["Severity"] == 3]
plt.scatter(cr_3["Start_Lng"], cr_3["Start_Lat"],s=0.3,c='tab:orange',marker='4',alpha=0.1,label='3')

cr_4 = df[df["Severity"] == 4]
plt.scatter(cr_4["Start_Lng"], cr_4["Start_Lat"],s=0.3,c='tab:red',marker='*',alpha=0.1,label='4')

plt.legend() 
            
plt.ylabel("y")
plt.xlabel("x")
plt.ylim(24.555269, 49.002201)
plt.xlim(-124.623833,-67.113167)

plt.show()
print("--- %s seconds ---" % (time.time() - start_time))

type(cr_1["Start_Lng"])
np.array(cr_1["Start_Lng"])

import time
start_time = time.time()



fig = plt.figure(figsize=(15,10))

#plt.scatter(df["Start_Lng"],df["Start_Lat"],s=20,c='r',marker='v',alpha=0.4,label='Simple Assault')


cr_1 = df[df["Severity"] == 1]
plt.scatter(np.array(cr_1["Start_Lng"]), np.array(cr_1["Start_Lat"]),s=20,c='tab:green',marker='3',alpha=0.5,label='1')

cr_2 = df[df["Severity"] == 2]
plt.scatter(np.array(cr_2["Start_Lng"]), np.array(cr_2["Start_Lat"]),s=20,c='tab:blue',marker='1',alpha=0.5,label='2')

cr_3 = df[df["Severity"] == 3]
plt.scatter(np.array(cr_3["Start_Lng"]), np.array(cr_3["Start_Lat"]),s=20,c='tab:orange',marker='4',alpha=0.4,label='3')

cr_4 = df[df["Severity"] == 4]
plt.scatter(np.array(cr_4["Start_Lng"]), np.array(cr_4["Start_Lat"]),s=20,c='tab:red',marker='*',alpha=0.4,label='4')

plt.legend() 
            
plt.ylabel("y")
plt.xlabel("x")
plt.ylim(24.555269, 49.002201)
plt.xlim(-124.623833,-67.113167)

plt.show()


print("--- %s seconds ---" % (time.time() - start_time))

fig = plt.figure(figsize=(60,40))

#plt.scatter(df["Start_Lng"],df["Start_Lat"],s=20,c='r',marker='v',alpha=0.4,label='Simple Assault')


cr_1 = df[df["Severity"] == 1]
plt.scatter(cr_1["Start_Lng"], cr_1["Start_Lat"],s=30,c='tab:blue',marker='*',alpha=0.5,label='1')

cr_2 = df[df["Severity"] == 2]
plt.scatter(cr_2["Start_Lng"], cr_2["Start_Lat"],s=30,c='tab:green',marker='*',alpha=0.5,label='2')

cr_3 = df[df["Severity"] == 3]
plt.scatter(cr_3["Start_Lng"], cr_3["Start_Lat"],s=30,c='tab:orange',marker='*',alpha=0.4,label='3')

cr_4 = df[df["Severity"] == 4]
plt.scatter(cr_4["Start_Lng"], cr_4["Start_Lat"],s=30,c='tab:red',marker='*',alpha=0.4,label='4')

plt.legend() 
            
plt.ylabel("y")
plt.xlabel("x")
plt.ylim(24.555269, 49.002201)
plt.xlim(-124.623833,-67.113167)


plt.show()

fig = plt.figure(figsize=(60,40))

#plt.scatter(df["Start_Lng"],df["Start_Lat"],s=20,c='r',marker='v',alpha=0.4,label='Simple Assault')


cr_2 = df[df["Severity"] == 2]
plt.scatter(cr_2["Start_Lng"], cr_2["Start_Lat"],s=50,c='green',marker='o',alpha=0.5,label='2')

cr_3 = df[df["Severity"] == 3]
plt.scatter(cr_3["Start_Lng"], cr_3["Start_Lat"],s=50,c='orange',marker='o',alpha=0.4,label='3')

cr_4 = df[df["Severity"] == 4]
plt.scatter(cr_4["Start_Lng"], cr_4["Start_Lat"],s=50,c='red',marker='o',alpha=0.4,label='4')


cr_1 = df[df["Severity"] == 1]
plt.scatter(cr_1["Start_Lng"], cr_1["Start_Lat"],s=50,c='blue',marker='o',alpha=0.5,label='1')

plt.legend() 
            
plt.ylabel("y")
plt.xlabel("x")
plt.ylim(24.555269, 49.002201)
plt.xlim(-124.623833,-67.113167)



plt.show()

df["Severity"].unique()

from google.colab import files
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(60,40))

#plt.scatter(df["Start_Lng"],df["Start_Lat"],s=20,c='r',marker='v',alpha=0.4,label='Simple Assault')


cr_1 = df[df["Severity"] == 1]
plt.scatter(cr_1["Start_Lng"], cr_1["Start_Lat"],s=5,c='tab:green',marker='*',alpha=0.5,label='1')

cr_2 = df[df["Severity"] == 2]
plt.scatter(cr_2["Start_Lng"], cr_2["Start_Lat"],s=5,c='tab:blue',marker='*',alpha=0.5,label='2')

cr_3 = df[df["Severity"] == 3]
plt.scatter(cr_3["Start_Lng"], cr_3["Start_Lat"],s=5,c='yellow',marker='*',alpha=0.4,label='3')

cr_4 = df[df["Severity"] == 4]
plt.scatter(cr_4["Start_Lng"], cr_4["Start_Lat"],s=5,c='crimson',marker='*',alpha=0.4,label='4')

plt.legend("美國交通意外（依據各種嚴重程度散步狀況，總共423萬筆") 
            
plt.ylabel("緯度")
plt.xlabel("經度")
plt.ylim(24.555269, 49.002201)
plt.xlim(-124.623833,-67.113167)

plt.savefig('US_CAR_ACCIDENT.pdf')
files.download('US_CAR_ACCIDENT.pdf')

plt.show()

fig = plt.figure(figsize=(60,40))

#plt.scatter(df["Start_Lng"],df["Start_Lat"],s=20,c='r',marker='v',alpha=0.4,label='Simple Assault')


cr_1 = df[df["Severity"] == 1]
plt.scatter(cr_1["Start_Lng"], cr_1["Start_Lat"],s=20,c='tab:green',marker='*',alpha=0.5,label='1')

cr_2 = df[df["Severity"] == 2]
plt.scatter(cr_2["Start_Lng"], cr_2["Start_Lat"],s=20,c='tab:blue',marker='*',alpha=0.5,label='2')

cr_3 = df[df["Severity"] == 3]
plt.scatter(cr_3["Start_Lng"], cr_3["Start_Lat"],s=20,c='tab:orange',marker='*',alpha=0.4,label='3')

cr_4 = df[df["Severity"] == 4]
plt.scatter(cr_4["Start_Lng"], cr_4["Start_Lat"],s=20,c='tomato',marker='*',alpha=0.4,label='4')

plt.legend("美國交通意外（依據各種嚴重程度散步狀況）") 
            
plt.ylabel("緯度")
plt.xlabel("經度")
plt.ylim(24.555269, 49.002201)
plt.xlim(-124.623833,-67.113167)


plt.show()

import seaborn as sns
sns.pairplot(df.iloc[0:10000,[3,23,24,25,26,27,28,29,30,31]],hue = "Severity",kind = "hist")

df.iloc[0:10000]

df.iloc[0:2][["Severity","Start_Lng"]]

df.iloc[0:2,23:31]

df.iloc[0:10000,[3,23,24,25,26,27,28,29,30]]

sns.pairplot(df.iloc[0:10000,[3,23,24,25,26,27,28,29,30,31]],hue = "Severity")

sns.pairplot(df.iloc[0:100000,[3,23,24,25,26,27,28,29,30,31]],kind = "reg",hue="Severity")

sns.pairplot(df.iloc[0:10000,[3,23,24,25,26,27,28,29,30,31]],kind = "hist")

sns.pairplot(df.iloc[0:10000,[3,23,24,25,26,27,28,29,30,31]],kind="kde")

sns.pairplot(df.iloc[0:100000,[3,23,24,25,26,27,28,29,30,31]],kind = "reg",hue="Severity")

z = df["Weather_Condition"].value_counts().head(5)

z

import seaborn as sns

count = df["Weather_Condition"].value_counts()[0:9]

dict(count)

my_df = pd.DataFrame(count.items())
ax = sns.barplot(x=0, y=1, data=my_df)
ax.set_xticklabels(ax.get_xticklabels(), rotation=40, ha="right")

sns.plot(x)

sns.histplot(x)

df.groupby("Weather_Condition").describe()

